name: flurry_analytics
description: A Flutter plugin to use Flurry Analytics. This version logs sessions, crash detections, simple event logging, UserId, and EndTimedEvent. We plan to add more features.
version: 0.1.0
author: Devansh Ramen <devanshramen@gmail.com>
homepage: https://github.com/devansh-ramen/flutter_flurry_analytics

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: perfectbuzz.devansh.flurryanalytics
    pluginClass: FlurryAnalyticsPlugin